[package]
name = "opuscule-tui-client"
version = "0.1.0"
authors = ["Paul Mazaitis <paul@mazaitis.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
